In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

docs = [
    "I love this movie",
    "This movie is great and inspiring",
    "I hate this boring movie",
    "This movie is not great"
]

# Bag of Words
cv = CountVectorizer()
bow = cv.fit_transform(docs)
print("BoW Vocabulary:", cv.get_feature_names_out())
print("BoW Matrix:\n", bow.toarray())

# TF-IDF
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(docs)
print("\nTF-IDF Vocabulary:", tfidf.get_feature_names_out())
print("TF-IDF Matrix:\n", tfidf_matrix.toarray())


BoW Vocabulary: ['and' 'boring' 'great' 'hate' 'inspiring' 'is' 'love' 'movie' 'not'
 'this']
BoW Matrix:
 [[0 0 0 0 0 0 1 1 0 1]
 [1 0 1 0 1 1 0 1 0 1]
 [0 1 0 1 0 0 0 1 0 1]
 [0 0 1 0 0 1 0 1 1 1]]

TF-IDF Vocabulary: ['and' 'boring' 'great' 'hate' 'inspiring' 'is' 'love' 'movie' 'not'
 'this']
TF-IDF Matrix:
 [[0.         0.         0.         0.         0.         0.
  0.8046125  0.41988018 0.         0.41988018]
 [0.51381313 0.         0.40509617 0.         0.51381313 0.40509617
  0.         0.268129   0.         0.268129  ]
 [0.         0.62688384 0.         0.62688384 0.         0.
  0.         0.32713399 0.         0.32713399]
 [0.         0.         0.47219392 0.         0.         0.47219392
  0.         0.31254032 0.59891811 0.31254032]]


In [ ]:
!pip install gensim
from gensim.models import Word2Vec

sentences = [
    ["i", "love", "nlp"],
    ["nlp", "is", "fun"],
    ["i", "love", "machine", "learning"]
]

model = Word2Vec(sentences, vector_size=5, window=2, min_count=1)
print(model.wv["love"])       # vector for "love"
print(model.wv.most_similar("nlp"))

[-0.14233617  0.12917745  0.17945977 -0.10030856 -0.07526743]
[('i', 0.4593397080898285), ('love', 0.2018294781446457), ('learning', 0.10980252921581268), ('is', 0.04115491732954979), ('fun', -0.0006994149298407137), ('machine', -0.11398053169250488)]


In [ ]:
from transformers import pipeline

# Pretrained BERT model for sentiment
analyzer = pipeline("sentiment-analysis")
print(analyzer("This movie was absolutely wonderful!"))


No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


[{'label': 'POSITIVE', 'score': 0.9998792409896851}]


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Sample data
texts = ["I love this movie", "This film was boring", "Great acting", "Not worth watching"]
labels = ["positive", "negative", "positive", "negative"]

# Split
X_train, X_test, y_train, y_test = train_test_split(texts, labels, test_size=0.5, random_state=42)

# TF-IDF
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

# Train
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

# Predict
pred = model.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))


Accuracy: 0.0
              precision    recall  f1-score   support

    negative       0.00      0.00      0.00       2.0
    positive       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_

In [ ]:
from transformers import pipeline
analyzer = pipeline("sentiment-analysis")
print(analyzer("This movie was absolutely wonderful!"))


No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


[{'label': 'POSITIVE', 'score': 0.9998792409896851}]


In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")
text = "Apple Inc. released the iPhone 15 in September 2023 for $799."
doc = nlp(text)

for ent in doc.ents:
    print(ent.text, ent.label_)


Apple Inc. ORG
September 2023 DATE
799 MONEY


In [ ]:
from transformers import pipeline
ner = pipeline("ner", grouped_entities=True)
text = "Elon Musk is the CEO of SpaceX and lives in Texas."
print(ner(text))


No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496 (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu
/usr/local

[{'entity_group': 'PER', 'score': np.float32(0.99912715), 'word': 'Elon Musk', 'start': 0, 'end': 9}, {'entity_group': 'ORG', 'score': np.float32(0.99908864), 'word': 'SpaceX', 'start': 24, 'end': 30}, {'entity_group': 'LOC', 'score': np.float32(0.99944466), 'word': 'Texas', 'start': 44, 'end': 49}]


In [ ]:
from transformers import pipeline

summarizer = pipeline("summarization")
text = """Natural Language Processing allows machines to understand, interpret,
and respond to human language. It combines computational linguistics,
machine learning, and deep learning models."""
summary = summarizer(text, max_length=30, min_length=10, do_sample=False)
print(summary[0]['summary_text'])


No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


 Natural Language Processing allows machines to understand, interpret and respond to human language . It combines computational linguistics, machine learning, and deep learning


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

docs = ["ChatGPT is a large language model developed by OpenAI for conversational AI."]
tfidf = TfidfVectorizer(stop_words='english')
X = tfidf.fit_transform(docs)

for word, score in zip(tfidf.get_feature_names_out(), X.toarray()[0]):
    print(word, round(score, 3))


ai 0.354
chatgpt 0.354
conversational 0.354
developed 0.354
language 0.354
large 0.354
model 0.354
openai 0.354


In [ ]:
!pip install keybert
from keybert import KeyBERT
kw_model = KeyBERT()
text = "Artificial intelligence and machine learning are transforming industries through automation."
keywords = kw_model.extract_keywords(text, top_n=5)
print(keywords)

[('automation', 0.6141), ('industries', 0.4742), ('learning', 0.3388), ('artificial', 0.2907), ('machine', 0.2906)]


In [ ]:
from transformers import pipeline

translator = pipeline("translation", model="Helsinki-NLP/opus-mt-en-fr")
text = "Artificial Intelligence is transforming education."
result = translator(text)
print(result[0]['translation_text'])


/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")
Device set to use cpu


L'intelligence artificielle transforme l'éducation.


In [ ]:
from transformers import pipeline
qa = pipeline("question-answering")
context = "Python is a popular programming language used for AI and data analysis."
print(qa(question="What is Python used for?", context=context))


No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


{'score': 0.8489867448806763, 'start': 50, 'end': 70, 'answer': 'AI and data analysis'}


Device set to use cpu


You: hello, how are you?


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=60) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


Bot: hello, how are you? my first post here, how are you doing?
You: exit


In [ ]:
from transformers import pipeline
chatbot = pipeline("text-generation", model="microsoft/DialoGPT-small")

while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        break
    response = chatbot(user_input, max_length=60, do_sample=True)
    print("Bot:", response[0]['generated_text'])


Device set to use cpu


You: exit


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

texts = ["I love AI", "I enjoy artificial intelligence", "The sky is blue"]
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(texts)

sim = cosine_similarity(X, X)
print(sim)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')
sentences = ["I love AI", "I enjoy artificial intelligence", "The weather is nice today"]
embeddings = model.encode(sentences)
similarity = util.cos_sim(embeddings, embeddings)
print(similarity)


tensor([[1.0000, 0.8196, 0.0683],
        [0.8196, 1.0000, 0.0281],
        [0.0683, 0.0281, 1.0000]])


In [ ]:
from transformers import pipeline
generator = pipeline("text-generation", model="gpt2")
print(generator("AI will change the", max_length=15))


Device set to use cpu
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=15) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': 'AI will change the way we have seen the game. This is all going to happen in the future, we can all work together to make the game we want to play better.\n\n"It\'s about time we move forward. It\'s about the future of the game. We have a huge team of players that are very passionate about this game and we want to build and grow. We\'ve got a lot of work to do and we have to take it into the next level. I think we\'ve got a lot to do and I think we\'ve got a lot to do together to create a better game."\n\nIt\'s still early days for the game, but the fans and the community have been very positive about its future. So, there will be a good opportunity for fans to come back to the game next year.\n\nThe game is a unique and exciting experience for both fans and players. We hope that the community can keep the momentum going for this game and we look forward to seeing you at E3.'}]


In [ ]:
from transformers import pipeline

analyzer = pipeline("sentiment-analysis")
print(analyzer("This phone is amazing and fast!"))
print(analyzer("The battery dies so quickly."))


No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


[{'label': 'POSITIVE', 'score': 0.9998371601104736}]
[{'label': 'NEGATIVE', 'score': 0.9996292591094971}]


In [ ]:
emo_model = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base")
print(emo_model("I can’t believe this happened!"))


Device set to use cpu


[{'label': 'surprise', 'score': 0.9388592839241028}]


In [ ]:
import whisper
model = whisper.load_model("base")
result = model.transcribe("sample_audio.mp3")
print(result["text"])


/usr/local/lib/python3.12/dist-packages/whisper/transcribe.py:132: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")


RuntimeError: Failed to load audio: ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
sample_audio.mp3: No such file or directory


In [ ]:
from gtts import gTTS
tts = gTTS("Welcome to Eduinx AI Lab.", lang="en")
tts.save("output.mp3")
print("Audio file 'output.mp3' generated successfully.")

Audio file 'output.mp3' generated successfully.


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding

model = Sequential([
    Embedding(input_dim=5000, output_dim=64, input_length=100),
    LSTM(128),
    Dense(1, activation='sigmoid')
])
model.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from transformers import pipeline

# Sentiment Classification
bert_classifier = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")
print(bert_classifier("The movie was absolutely fantastic!"))


Device set to use cpu


[{'label': 'POSITIVE', 'score': 0.9998741149902344}]


In [ ]:
from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")
print(generator("Once upon a time in a world of AI,", max_length=25))


Device set to use cpu
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=25) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': 'Once upon a time in a world of AI, most people didn\'t know what to do with their minds. But they have a lot to learn.\n\nToday we\'re seeing the first real evidence of this in computer programming, which is what makes it possible to program your emotions and behaviors.\n\nFor example, I wrote a simple script to simulate a fight scene in my game, The Last of Us. I asked the audience to "play" the scene by playing through the main characters. I asked them to make their own character voices, and then asked them to play the game.\n\nIn a game like this, when I play through one character, I want to play through every other character. The audience is watching me play through the whole game, the characters are playing through the same scenes, and the game is about the same as it was before.\n\nThe first thing to note is that each character has different abilities and reactions. When I play through my character, I\'m able to react to the environment and the characters\' a

In [ ]:
from transformers import pipeline

t5 = pipeline("text2text-generation", model="google/flan-t5-small")
print(t5("summarize: Artificial intelligence enables machines to think like humans.", max_length=30))


Device set to use cpu
Both `max_new_tokens` (=256) and `max_length`(=30) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': 'Artificial intelligence enables machines to think like humans.'}]


In [ ]:
from transformers import pipeline
summarizer = pipeline("summarization")
print(summarizer("AI helps machines learn patterns in data and make predictions.", max_length=25))


No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu
Your min_length=56 must be inferior than your max_length=25.
Your max_length is set to 25, but your input_length is only 13. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=6)
/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py:1633: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (25). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length.
  warnings.warn(


[{'summary_text': ' AI helps machines learn patterns in data and make predictions . AI helps machine learn patterns of data and makes predictions .'}]


In [ ]:
!pip install langchain-community
from langchain import OpenAI, LLMChain, PromptTemplate

prompt = PromptTemplate(input_variables=["topic"], template="Explain {topic} in simple terms.")
llm = OpenAI(model_name="gpt-4-turbo") # Changed 'model' to 'model_name'
chain = LLMChain(prompt=prompt, llm=llm)

print(chain.run("reinforcement learning"))

In [ ]:
# First, let's upgrade the transformers and datasets libraries to ensure compatibility.
!pip install --upgrade transformers datasets

import torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments, IntervalStrategy

# NOTE: If you encounter 'TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy',
# please restart your Python runtime (e.g., Runtime > Restart runtime in Colab) and re-run this cell.

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Load dataset
dataset = load_dataset("imdb")

# Tokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
def preprocess(batch):
    # Ensure labels are of type long for CrossEntropyLoss
    batch["labels"] = batch["label"]
    return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=128)

# Map function might take time, running on a subset for demonstration
processed_dataset = dataset.map(preprocess, batched=True)

# Filter out 'label' from the dataset features, as 'labels' will be used by the model
processed_dataset = processed_dataset.remove_columns(["text", "label"])

# Model
model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2).to(device)

# Training setup
# Use IntervalStrategy for evaluation_strategy with LoggingStrategy
args = TrainingArguments(
    output_dir="./results",
    eval_strategy=IntervalStrategy.EPOCH,
    save_strategy=IntervalStrategy.EPOCH, # Changed to match eval_strategy
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2,
    logging_dir="./logs",
    logging_steps=100,
    save_steps=500,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy"
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=processed_dataset["train"].select(range(2000)), # Using a smaller subset for faster execution
    eval_dataset=processed_dataset["test"].select(range(500))    # Using a smaller subset for faster execution
)

try:
    print("Starting model training...")
    trainer.train()
    print("Model training completed.")
except KeyboardInterrupt:
    print("Training interrupted by user. Current state saved (if any).")

Using device: cpu


Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Starting model training...


/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, Trainer, TrainingArguments

model_name = "t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Sample training data
train_texts = ["summarize: Artificial intelligence enables machines to think like humans."]
train_labels = ["AI helps machines think like humans."]

# Tokenize
inputs = tokenizer(train_texts, truncation=True, padding="max_length", max_length=128, return_tensors="pt")
labels = tokenizer(train_labels, truncation=True, padding="max_length", max_length=64, return_tensors="pt")["input_ids"]

# Forward pass
outputs = model(**inputs, labels=labels)
loss = outputs.loss
print(loss)


In [ ]:
model.save_pretrained("./my_finetuned_model")
tokenizer.save_pretrained("./my_finetuned_model")


In [ ]:
from transformers import pipeline
model = pipeline("sentiment-analysis", model="./my_finetuned_model")


In [ ]:
from langchain.vectorstores import FAISS
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains import RetrievalQA
from langchain.llms import OpenAI

# 1. Load and split document
from langchain.document_loaders import TextLoader
loader = TextLoader("policy.txt")
docs = loader.load()
splitter = CharacterTextSplitter(chunk_size=500, chunk_overlap=50)
chunks = splitter.split_documents(docs)

# 2. Create embeddings & vector store
embeddings = OpenAIEmbeddings()
db = FAISS.from_documents(chunks, embeddings)

# 3. Build retriever + QA chain
retriever = db.as_retriever()
qa = RetrievalQA.from_chain_type(llm=OpenAI(model="gpt-4-turbo"), chain_type="stuff", retriever=retriever)

# 4. Ask question
query = "What is the maternity leave duration?"
print(qa.run(query))


In [ ]:
from langchain import OpenAI, LLMChain, PromptTemplate

prompt = PromptTemplate(input_variables=["topic"], template="Explain {topic} in simple terms.")
llm = OpenAI(model="gpt-4-turbo")
chain = LLMChain(prompt=prompt, llm=llm)

print(chain.run("reinforcement learning"))


In [ ]:
from crewai import Agent, Task, Crew

planner = Agent(name="Planner", role="Decompose request", model="gpt-4-turbo")
analyst = Agent(name="Analyst", role="Summarize retrieved data", model="gpt-4-turbo")

task = Task(description="Find 3 key trends in AI education", agent=planner)
crew = Crew(agents=[planner, analyst])
crew.run()


In [ ]:
pip install streamlit langchain faiss-cpu openai python-dotenv


In [ ]:
OPENAI_API_KEY = "your_api_key"


In [ ]:
import streamlit as st
st.title("📚 Enterprise Policy Chatbot")

query = st.text_input("Ask a question about company policies:")


In [ ]:
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import FAISS
from langchain.embeddings.openai import OpenAIEmbeddings

from langchain.document_loaders import DirectoryLoader
loader = DirectoryLoader("docs/", glob="*.pdf")
docs = loader.load()

splitter = CharacterTextSplitter(chunk_size=500, chunk_overlap=50)
chunks = splitter.split_documents(docs)

embeddings = OpenAIEmbeddings()
db = FAISS.from_documents(chunks, embeddings)


In [ ]:
from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI

qa = RetrievalQA.from_chain_type(
    llm=ChatOpenAI(model_name="gpt-4-turbo"),
    retriever=db.as_retriever(),
    chain_type="stuff"
)

if query:
    st.write("**Answer:**", qa.run(query))


In [ ]:
from sklearn.metrics import f1_score, accuracy_score

true = ["yes", "no", "yes", "no"]
pred = ["yes", "yes", "yes", "no"]

print("Accuracy:", accuracy_score(true, pred))
print("F1 Score:", f1_score(true, pred, pos_label="yes"))


In [ ]:
from transformers import pipeline
detector = pipeline("text-classification", model="unitary/toxic-bert")
print(detector("I hate you!"))


In [ ]:
from openai import OpenAI
client = OpenAI()

# Zero-Shot
prompt1 = "Classify the sentiment: 'I love this product!'"
# Few-Shot
prompt2 = """Classify sentiment:
1. 'This phone is terrible.' → Negative
2. 'I adore this device.' → Positive
3. 'I love this product!' →"""

print(client.chat.completions.create(model="gpt-4-turbo", messages=[{"role": "user", "content": prompt2}]))


In [ ]:
from langchain.agents import load_tools, initialize_agent
from langchain.llms import OpenAI

llm = OpenAI(model_name="gpt-4-turbo")
tools = load_tools(["serpapi", "llm-math"], llm=llm)

agent = initialize_agent(tools, llm, agent_type="zero-shot-react-description", verbose=True)
agent.run("What is the square root of 144 multiplied by today's temperature in Delhi?")


In [ ]:
from langgraph.graph import Graph
from langchain.chat_models import ChatOpenAI

# Define agents
llm = ChatOpenAI(model_name="gpt-4-turbo")

def planner(state):
    return {"task": f"Break down goal: {state['query']}"}

def retriever(state):
    return {"data": f"Searching info about {state['task']}"}

def summarizer(state):
    return {"summary": f"Summarizing {state['data']}"}

# Build Graph
graph = Graph()
graph.add_node("planner", planner)
graph.add_node("retriever", retriever)
graph.add_node("summarizer", summarizer)

graph.add_edge("planner", "retriever")
graph.add_edge("retriever", "summarizer")

# Run workflow
result = graph.run({"query": "AI impact on education"})
print(result["summary"])


In [ ]:
from langchain.memory import ConversationBufferMemory
memory = ConversationBufferMemory(memory_key="chat_history")


In [ ]:
pip install langchain langgraph streamlit openai


In [ ]:
OPENAI_API_KEY=your_api_key_here


In [ ]:
# app.py
import streamlit as st
from langgraph.graph import Graph
from langchain.chat_models import ChatOpenAI

st.title("🧭 Multi-Agent Workflow Demo (LangGraph + Streamlit)")

query = st.text_input("Enter your topic or problem:")

# Define basic agents
llm = ChatOpenAI(model_name="gpt-4-turbo")

def planner(state): return {"task": f"Break down: {state['query']}"}
def retriever(state): return {"info": f"Retrieving data about {state['task']}"}
def analyzer(state): return {"analysis": f"Analyzing {state['info']}"}
def presenter(state): return {"output": f"Final summary → {state['analysis']}"}

# Build graph
graph = Graph()
graph.add_node("planner", planner)
graph.add_node("retriever", retriever)
graph.add_node("analyzer", analyzer)
graph.add_node("presenter", presenter)

graph.add_edge("planner", "retriever")
graph.add_edge("retriever", "analyzer")
graph.add_edge("analyzer", "presenter")

if query:
    result = graph.run({"query": query})
    st.subheader("🧩 Workflow Output")
    st.write(result["output"])


In [ ]:
from langchain.memory import ConversationBufferMemory
memory = ConversationBufferMemory(memory_key="chat_history")

# Example: keep agent interactions for later queries
if "history" not in st.session_state:
    st.session_state.history = []


In [ ]:
with st.expander("🔍 See Internal Reasoning"):
    st.json(result)


In [ ]:
from langchain.agents import load_tools, initialize_agent
tools = load_tools(["serpapi", "llm-math"], llm=llm)
